### ISSUE TITLE
Deploying Customized store Applications

### ISSUE THREAD

**Issue by vinay2099** [ServiceNow/servicenow-cicd-azure-extension#19]
@chiarnglin Hope you are doing good.We had a question related to customized store applications.

The present existing code contains version that works for a new application but when we customize any application from the store, in servicenow we have two version numbers.(customized version and base version : mentioned in below link)
https://docs.servicenow.com/bundle/quebec-application-development/page/build/applications/task/manage-customizations-store-apps.html

So, for these applications, how can we deploy in pipeline using this code.
Which attribute has to be used for customized version and base version?

**Comment by zostrum** [comment]
Hello!

First of all, I'd suggest checking docs -
https://developer.servicenow.com/dev.do#!/reference/api/quebec/rest/cicd-api#cicd-POST-app_repo-install?navFilter=cicd
Don't forget to switch to Quebec.
As you can see, baseAppVersion and autoUpgradeBaseApp has default values
and not mandatory fields.
If you want to use them, please set up Github secrets(
SNOW_BASE_APP_VERSION, SNOW_AUTO_UPGRADE_BASE_APP), then add
  baseAppVersion: ${{ secrets.SNOW_BASE_APP_VERSION }}
  autoUpgradeBaseApp: ${{ secrets.SNOW_AUTO_UPGRADE_BASE_APP }}
to your workflow file.

Also, you can verify this step in a manual way by using Postman(or another
REST client) and POST query with following format:
https://{{APP_CLIENT_INST}}
/api/sn_cicd/app_repo/install?version={{VERSION}}&scope={{APP_SCOPE}}&auto_upgrade_base_app={{TRUE/FALSE}}&base_app_version={{BASE_VERSION}}

Thanks, Stan

вт, 13 квіт. 2021 о 10:25 Vinay ***@***.***> пише:

**Comment by vinay2099** [comment]
Hello Stan,

Thanks for your response and any idea if this is already incorporated in this azure extension?

Kind regards,
Vinay

**Comment by zostrum** [comment]
As far as I know it's in schedule (up to 2-3 month).

**Comment by chiarnglin** [comment]
Hi @vinay2099,
We're currently in the process of updating our external integrations (including Azure Pipelines extension) for our Quebec features, including application customizations for Store apps. @zostrum (Stan) is our developer working on the updates. I don't have an exact date for the release yet, but we'll work on getting these updates out as soon as we can for our early Quebec adopters. 
On a separate note, I'd like to jump on a call with your team since it's been a few months, sync up with you on roadmap and your top pain points or feature requests! Can you reach out to me at chiarng.lin@servicenow.com? 
Thanks,
Chiarng
